import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ShieldCheck,LockKeyhole,Mail,Eye,EyeOff,ArrowRight,Loader2} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Brand,ErrorNotice} from '../components/shared';
import {useApp} from '../app/context';
import {post} from '../api/client';
import {Session} from '../api/auth';
export default function ExpertLoginPage(){
 const {t,accept}=useApp(),navigate=useNavigate();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{accept(await post<Session>('/auth/expert/login',{email:email.trim(),password}));setPassword('');navigate('/expert');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <div className="login-page"><img className="login-background" src="/images/wheat-hero.jpg" alt="Green wheat field"/><div className="login-scrim"/><header className="login-header"><Brand light/><Link className="btn expert-back" data-testid="expert-to-farmer-login" to="/login">{t('Farmer sign-in','किसान साइन-इन','ਕਿਸਾਨ ਸਾਈਨ-ਇਨ')}</Link></header><div className="login-content"><p className="eyebrow" data-testid="expert-login-eyebrow">{t('EXPERT WORKSPACE','विशेषज्ञ कार्यक्षेत्र','ਮਾਹਰ ਵਰਕਸਪੇਸ')}</p><h1 data-testid="expert-login-title">{t('Your knowledge.','आपका ज्ञान।','ਤੁਹਾਡਾ ਗਿਆਨ।')}<br/><em>{t('Their next good harvest.','उनकी अगली अच्छी फसल।','ਉਨ੍ਹਾਂ ਦੀ ਅਗਲੀ ਚੰਗੀ ਫ਼ਸਲ।')}</em></h1><div className="login-form-box"><div className="modal-icon"><ShieldCheck size={23}/></div><h2 data-testid="expert-signin-heading">{t('Expert sign-in','विशेषज्ञ साइन-इन','ਮਾਹਰ ਸਾਈਨ-ਇਨ')}</h2><p>{t('Access for approved agricultural experts.','स्वीकृत कृषि विशेषज्ञों के लिए प्रवेश।','ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਖੇਤੀ ਮਾਹਰਾਂ ਲਈ ਦਾਖਲਾ।')}</p><ErrorNotice message={error}/><form onSubmit={submit}><label htmlFor="expert-email">{t('Email address','ईमेल पता','ਈਮੇਲ ਪਤਾ')}</label><div className="phone-input login-identity-field"><Mail size={17}/><input id="expert-email" data-testid="expert-email" type="email" autoComplete="username" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></div><label htmlFor="expert-password">{t('Password','पासवर्ड','ਪਾਸਵਰਡ')}</label><div className="phone-input"><LockKeyhole size={17}/><input id="expert-password" data-testid="expert-password" type={visible?'text':'password'} autoComplete="current-password" required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/><button type="button" className="icon-button" data-testid="expert-toggle-password" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={16}/>:<Eye size={16}/>}</button></div><Button className="btn primary full" type="submit" data-testid="expert-login-submit" disabled={busy}>{busy?<Loader2 className="spin" size={17}/>:<><ShieldCheck size={17}/>{t('Sign in securely','सुरक्षित साइन-इन','ਸੁਰੱਖਿਅਤ ਸਾਈਨ-ਇਨ')}<ArrowRight size={17}/></>}</Button></form><p className="expert-account-note" data-testid="expert-account-note">{t('Your administrator creates your expert account. There is no public expert registration or demo bypass.','आपका व्यवस्थापक विशेषज्ञ खाता बनाता है। सार्वजनिक पंजीकरण या डेमो प्रवेश उपलब्ध नहीं है।','ਤੁਹਾਡਾ ਪ੍ਰਬੰਧਕ ਮਾਹਰ ਖਾਤਾ ਬਣਾਉਂਦਾ ਹੈ। ਜਨਤਕ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਜਾਂ ਡੈਮੋ ਦਾਖਲਾ ਨਹੀਂ ਹੈ।')}</p></div></div></div>;
}