import { useEffect, useState } from 'react';
import { Loader2, MapPin, Sprout } from 'lucide-react';
import { Button } from './ui/button';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from './ui/dialog';
import { ErrorNotice } from './shared';
import { FarmMap } from './FarmMap';
import { post } from '../api/client';
import { useApp } from '../app/context';
const AREA_UNITS = { Acre: 1, Hectre: 2.47105, 'Square Meter': 1 / 4046.8564224, Bagha: 0.625, guntha: 1 / 40, cent: 1 / 100, katha: 1 / 20 } as const;
export const FieldForm = ({open,onClose,onSaved}: {open:boolean;onClose:()=>void;onSaved:()=>void}) => {
 const {t}=useApp();const [busy,setBusy]=useState(false),[error,setError]=useState('');const [pin,setPin]=useState<[number,number]|null>(null);
 useEffect(()=>{if(!open)return;const mount=()=>{const input=document.querySelector<HTMLInputElement>('[data-testid="field-acreage-input"]');const label=input?.closest('label');if(!input||!label||label.querySelector('[data-testid="field-area-unit"]'))return;const select=document.createElement('select');select.dataset.testid='field-area-unit';select.name='area_unit';select.setAttribute('aria-label','Area unit');select.className='field-area-unit';Object.keys(AREA_UNITS).forEach(unit=>{const option=document.createElement('option');option.value=unit;option.textContent=unit;select.appendChild(option);});const group=document.createElement('div');group.className='area-input-group';input.replaceWith(group);group.append(input,select);};const observer=new MutationObserver(mount);observer.observe(document.body,{childList:true,subtree:true});mount();return()=>observer.disconnect();},[open]);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);setError('');try{const soil:Record<string,number>={};['ph','nitrogen','phosphorus','potassium'].forEach(key=>{if(fd.get(key)!=='')soil[key]=Number(fd.get(key));});const amount=Number(fd.get('acreage'));const unit=String(fd.get('area_unit')||'Acre') as keyof typeof AREA_UNITS;await post('/fields',{name:fd.get('name'),crop:fd.get('crop'),location:fd.get('location'),acreage:amount*AREA_UNITS[unit],sowing_date:fd.get('sowing_date'),soil_profile:soil,latitude:pin?.[0]??null,longitude:pin?.[1]??null});onSaved();onClose();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="field-dialog" data-testid="field-dialog"><div className="modal-icon"><Sprout size={23}/></div><DialogTitle className="serif-title" data-testid="field-form-title">{t('A new field, a new beginning.','एक नया खेत, एक नई शुरुआत।','ਨਵਾਂ ਖੇਤ, ਨਵੀਂ ਸ਼ੁਰੂਆਤ।')}</DialogTitle><DialogDescription data-testid="field-form-description">{t('Let’s get to know your little piece of earth.','आइए आपके खेत को जानें।','ਆਓ ਤੁਹਾਡੇ ਖੇਤ ਨੂੰ ਜਾਣੀਏ।')}</DialogDescription><ErrorNotice message={error}/><form className="field-form" onSubmit={submit}><div className="form-grid"><label className="span-2">{t('Field name','खेत का नाम','ਖੇਤ ਦਾ ਨਾਮ')}<input data-testid="field-name-input" name="name" required minLength={2} maxLength={80} placeholder="e.g. The north field"/></label><label>{t('Crop','फसल','ਫ਼ਸਲ')}<select data-testid="field-crop-input" name="crop" required>{['Wheat','Rice','Cotton','Maize','Mustard','Vegetables'].map(c=><option key={c}>{c}</option>)}</select></label><label>{t('Area (acres)','क्षेत्रफल (एकड़)','ਖੇਤਰ (ਏਕੜ)')}<input data-testid="field-acreage-input" name="acreage" type="number" min="0.01" max="100000" step="0.01" required placeholder="4.5"/></label><label>{t('Village / district','गाँव / जिला','ਪਿੰਡ / ਜ਼ਿਲ੍ਹਾ')}<input data-testid="field-location-input" name="location" required minLength={2} maxLength={160} placeholder="Ludhiana, Punjab"/></label><label>{t('Sowing date','बुवाई की तारीख','ਬਿਜਾਈ ਦੀ ਤਾਰੀਖ')}<input data-testid="field-sowing-date" name="sowing_date" type="date" required max={new Date().toLocaleDateString('en-CA')}/></label></div><details className="soil-details"><summary data-testid="soil-details-toggle">{t('Soil values','मिट्टी के मान','ਮਿੱਟੀ ਦੇ ਮੁੱਲ')} <span>{t('Optional','वैकल्पिक','ਵਿਕਲਪਿਕ')}</span></summary><div className="form-grid">{[['ph','pH','14'],['nitrogen','Nitrogen (kg/ha)','2000'],['phosphorus','Phosphorus (kg/ha)','2000'],['potassium','Potassium (kg/ha)','2000']].map(([key,label,max])=><label key={key}>{label}<input data-testid={`field-soil-${key}`} name={key} type="number" min="0" max={max} step="0.01" placeholder="Not provided"/></label>)}</div></details><details className="soil-details"><summary data-testid="field-map-toggle"><MapPin size={15}/>{t('Pin your field on the map','नक्शे पर खेत चुनें','ਨਕਸ਼ੇ ਤੇ ਖੇਤ ਚੁਣੋ')}<span>{t('Optional','वैकल्पिक','ਵਿਕਲਪਿਕ')}</span></summary><FarmMap selected={pin} onSelect={(lat,lng)=>setPin([lat,lng])}/>{pin&&<small data-testid="field-pin-coordinates">{pin[0]}, {pin[1]}</small>}</details><div className="form-footer"><Button variant="outline" type="button" data-testid="field-cancel" onClick={onClose}>{t('Cancel','रद्द करें','ਰੱਦ ਕਰੋ')}</Button><Button className="btn primary" data-testid="field-save" type="submit" disabled={busy}>{busy?<Loader2 size={16} className="spin"/>:<Sprout size={16}/>} {t('Save field','खेत सहेजें','ਖੇਤ ਸੰਭਾਲੋ')}</Button></div></form></DialogContent></Dialog>;
};