import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Check, Clock3, Leaf, Loader2, AlertCircle } from 'lucide-react';
import { useApp } from '../app/context';
import { Advisory } from '../types';

export const Brand = ({ light = false }: { light?: boolean }) => <Link to="/" className={`brand ${light ? 'light' : ''}`} data-testid={light ? 'sidebar-brand' : 'login-brand'}><span className="brand-icon"><Leaf size={26}/></span><span>Sahaayak<small>खेत का साथी · Your farming companion</small></span></Link>;
export const PageHeading = ({ eyebrow, title, description, action }: {eyebrow?: string; title: string; description?: string; action?: React.ReactNode}) => <div className="page-heading"><div>{eyebrow && <p className="eyebrow" data-testid="page-eyebrow">{eyebrow}</p>}<h1 data-testid="page-title">{title}</h1>{description && <p className="page-description" data-testid="page-description">{description}</p>}</div>{action}</div>;
export const StatusBadge = ({status, id = status}: {status: string; id?: string}) => { const {t} = useApp(); const labels: Record<string,string> = {verified: t('Expert verified', 'विशेषज्ञ द्वारा सत्यापित', 'ਮਾਹਰ ਵੱਲੋਂ ਤਸਦੀਕ'), pending_review: t('In expert review', 'विशेषज्ञ समीक्षा में', 'ਮਾਹਰ ਸਮੀਖਿਆ ਵਿੱਚ'), needs_information: t('More information needed', 'अधिक जानकारी चाहिए', 'ਹੋਰ ਜਾਣਕਾਰੀ ਚਾਹੀਦੀ ਹੈ'), processing: t('Processing', 'प्रक्रिया में', 'ਕਾਰਵਾਈ ਜਾਰੀ'), failed: t('Processing failed', 'प्रक्रिया विफल', 'ਕਾਰਵਾਈ ਅਸਫਲ')}; return <span data-testid={`status-${id}`} className={`status ${status}`}>{status === 'verified' ? <Check size={12}/> : <Clock3 size={12}/>} {labels[status] || status}</span>; };
export const Loading = () => <div className="loading-state" data-testid="loading-state"><Loader2 className="spin"/><span>Just a moment…</span></div>;
export const ErrorNotice = ({message}: {message: string}) => message ? <div className="notice warning" role="alert" data-testid="error-notice"><AlertCircle size={18}/>{message}</div> : null;
export const Empty = ({title, description, to, action}: {title: string; description: string; to?: string; action?: string}) => <div className="empty-state" data-testid="empty-state"><Leaf size={32}/><h2>{title}</h2><p>{description}</p>{to && <Link data-testid="empty-action" className="btn primary" to={to}>{action}<ArrowRight size={16}/></Link>}</div>;
export const AdvisoryRow = ({item, expert = false}: {item: Advisory; expert?: boolean}) => <Link to={expert ? `/expert/cases/${item.id}` : `/advisories/${item.id}`} className="advisory-row" data-testid={`advisory-${item.id}`}><div className={`crop-icon ${item.crop.toLowerCase()}`}><Leaf size={20}/></div><div className="advisory-row-body"><h3 data-testid={`advisory-title-${item.id}`}>{item.title}</h3><p data-testid={`advisory-meta-${item.id}`}>{item.crop} <span>·</span> {expert ? item.farmer_name : item.field_name} <span>·</span> {new Date(item.created_at).toLocaleDateString('en-IN', {day:'numeric',month:'short'})}</p></div><StatusBadge status={item.status} id={item.id}/><ArrowUpRight className="row-arrow" size={18}/></Link>;
export const SectionTitle = ({title, to, link = 'View all'}: {title: string; to?: string; link?: string}) => <div className="section-title"><h2 data-testid={`section-${title.replace(/\s/g,'-').toLowerCase()}`}>{title}</h2>{to && <Link to={to} data-testid={`view-${to.replace(/\//g,'')}`}>{link}<ArrowRight size={14}/></Link>}</div>;