import {Link} from 'react-router-dom';
import {CloudSun,Droplets,Wind,MapPin,RefreshCw,LocateFixed,Loader2} from 'lucide-react';
import {useApp} from '../app/context';
import {useWeather} from '../hooks/useWeather';
import {useGeolocation} from '../hooks/useGeolocation';
export const WeatherCard=({query='',locationControls=true}:{query?:string;locationControls?:boolean})=>{
 const {t}=useApp();const geo=useGeolocation();const {data,loading,error,refresh}=useWeather(geo.coordinates?`latitude=${geo.coordinates[0]}&longitude=${geo.coordinates[1]}`:query);
 const available=data?.temperature!=null;const fresh=available&&!data?.stale&&!error;
 return <section className="weather-card connected-weather" data-testid="connected-weather"><div className="weather-header"><span>{t('Around your farm','आपके खेत के आसपास','ਤੁਹਾਡੇ ਖੇਤ ਦੇ ਆਲੇ-ਦੁਆਲੇ')}</span><span className="subtle-pill" data-testid="weather-mode">{loading?'UPDATING':fresh?'CURRENT':available?'OLDER DATA':'NO DATA'}</span><button className="icon-button weather-refresh" data-testid="weather-refresh" aria-label="Refresh weather" disabled={loading} onClick={refresh}><RefreshCw size={14} className={loading?'spin':''}/></button></div><p className="weather-location" data-testid="weather-location"><MapPin size={13}/>{data?.location||t('Select a field or share your location','खेत चुनें या स्थान साझा करें','ਖੇਤ ਚੁਣੋ ਜਾਂ ਥਾਂ ਸਾਂਝੀ ਕਰੋ')}</p><div className="weather-main"><span data-testid="weather-temperature">{available?Math.round(data!.temperature!):'—'}<sup>°C</sup></span><CloudSun size={60} strokeWidth={1.1}/></div><div className="weather-caption" data-testid="weather-condition">{available?data?.condition:t('Weather is not available yet.','मौसम की जानकारी अभी उपलब्ध नहीं है।','ਮੌਸਮ ਦੀ ਜਾਣਕਾਰੀ ਅਜੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।')}</div><div className="weather-details"><span><Droplets size={15}/><strong data-testid="weather-precipitation">{data?.precipitation??'—'}</strong><small>mm{data?.precipitation_interval_seconds?` / ${data.precipitation_interval_seconds/60} min`:''}</small></span><span><Wind size={16}/><strong data-testid="weather-wind">{data?.wind_speed??'—'}</strong><small>km/h</small></span></div>{data?.observed_at&&<p className="weather-footnote" data-testid="weather-observed-at">{new Date(data.observed_at).toLocaleString()} · {data.provider}<br/>{data.source_kind} · {data.humidity??'—'}% {t('humidity','नमी','ਨਮੀ')}</p>}{(error||data?.reason||geo.error)&&<p className="weather-message" role="status" data-testid="weather-message">{geo.error||error||data?.reason}</p>}<div className="weather-actions">{locationControls&&<button className="text-button" data-testid="weather-use-location" disabled={geo.locating} onClick={geo.locate}>{geo.locating?<Loader2 className="spin" size={13}/>:<LocateFixed size={13}/>} {t('Use my location','मेरा स्थान उपयोग करें','ਮੇਰੀ ਥਾਂ ਵਰਤੋ')}</button>}<Link to="/location" state={geo.coordinates?{coordinates:geo.coordinates}:undefined} data-testid="weather-view-map">{t('View map','नक्शा देखें','ਨਕਸ਼ਾ ਵੇਖੋ')} →</Link></div><p className="weather-footnote" data-testid="weather-attribution">{data?.attribution||'Weather provider data'} · {t('Not a field diagnosis','खेत का निदान नहीं','ਖੇਤ ਦੀ ਤਸ਼ਖ਼ੀਸ ਨਹੀਂ')}</p></section>;
};