import {useEffect,useState} from 'react';
import {APIProvider,Map,AdvancedMarker,Pin,useMap} from '@vis.gl/react-google-maps';
import {FarmField} from '../types';
interface Props {apiKey:string;mapId:string;fields:FarmField[];selected?:[number,number]|null;onSelect?:(lat:number,lon:number)=>void;onFailure:()=>void}
const FitMap=({fields,selected}:{fields:FarmField[];selected?:[number,number]|null})=>{const map=useMap();useEffect(()=>{if(!map)return;const points=fields.filter(f=>f.latitude!=null&&f.longitude!=null).map(f=>({lat:f.latitude!,lng:f.longitude!}));if(selected)points.push({lat:selected[0],lng:selected[1]});if(points.length===1){map.setCenter(points[0]);map.setZoom(14);}else if(points.length>1){const bounds=new google.maps.LatLngBounds();points.forEach(p=>bounds.extend(p));map.fitBounds(bounds,40);}},[map,fields,selected]);return null;};
export const GoogleFarmMap=({apiKey,mapId,fields,selected,onSelect,onFailure}:Props)=>{
 const [loaded,setLoaded]=useState(false);
 useEffect(()=>{const previous=(window as any).gm_authFailure;(window as any).gm_authFailure=onFailure;return()=>{(window as any).gm_authFailure=previous;};},[onFailure]);
 return <div className="farm-map-wrap"><APIProvider apiKey={apiKey} onLoad={()=>setLoaded(true)} onError={onFailure}><Map className="farm-map" data-testid="google-farm-map" defaultCenter={{lat:20.59,lng:78.96}} defaultZoom={5} mapId={mapId} gestureHandling="cooperative" onClick={event=>{const point=event.detail.latLng;if(point)onSelect?.(Number(point.lat.toFixed(6)),Number(point.lng.toFixed(6)));}}><FitMap fields={fields} selected={selected}/>{fields.filter(f=>f.latitude!=null&&f.longitude!=null).map(f=><AdvancedMarker key={f.id} position={{lat:f.latitude!,lng:f.longitude!}} title={`${f.name} · ${f.crop}`}><Pin background="#244f3e" borderColor="#ffffff" glyphColor="#ffffff"/></AdvancedMarker>)}{selected&&<AdvancedMarker position={{lat:selected[0],lng:selected[1]}} title="Selected location"><Pin background="#c4a45c" borderColor="#ffffff" glyphColor="#ffffff"/></AdvancedMarker>}</Map></APIProvider>{!loaded&&<div className="map-loading" data-testid="google-map-loading">Loading Google Maps…</div>}</div>;
};