"""Versioned curated retrieval; a general source never supports a diagnosis/dosage."""
from ..db import db
from .copy import GENERAL_ADVISORY
SOURCE = {'id': 'fao-ipm-2026', 'title': 'Integrated Pest Management', 'publisher': 'FAO', 'region': 'Global', 'crop': 'General', 'document_version': 'Web snapshot · 2026-09-08', 'url': 'https://www.fao.org/pest-and-pesticide-management/ipm/integrated-pest-management/en/', 'verified': True, 'scope': 'General principles only; not a diagnosis or pesticide label.', 'excerpt': 'IPM combines biological, chemical, physical and crop-specific management strategies to grow healthy crops and minimize pesticide use and associated risks.'}
async def retrieve(crop, query):
    source = await db.knowledge_sources.find_one({'id': SOURCE['id']}, {'_id': 0})
    return [source] if source else []
COPY = {
 'en': {'title': 'Start with observation, not a treatment', 'summary': 'This is general agricultural guidance, not a diagnosis. The available information cannot confirm a disease, nutrient deficiency, or crop risk.', 'steps': ['Observe affected and unaffected plants. Record when symptoms started and whether they are spreading.', 'Photograph the whole plant and both sides of affected leaves in natural light. Share recent irrigation and input history with an agricultural expert.', 'Prefer prevention and ecological pest management. Do not select a pesticide or dosage from symptoms alone.'], 'safety': 'No pesticide, fertilizer dosage, yield prediction, or guaranteed outcome is provided. Contact a local agricultural expert before treatment.'},
 'hi': {'title': 'पहले निरीक्षण करें, फिर उपचार चुनें', 'summary': 'यह सामान्य कृषि मार्गदर्शन है, निदान नहीं। उपलब्ध जानकारी से रोग, पोषक तत्वों की कमी या फसल जोखिम की पुष्टि नहीं हो सकती।', 'steps': ['प्रभावित और स्वस्थ पौधों का निरीक्षण करें। लक्षण कब शुरू हुए और क्या वे फैल रहे हैं, लिखें।', 'प्राकृतिक रोशनी में पूरे पौधे और पत्तियों के दोनों तरफ की तस्वीर लें। सिंचाई और हाल के कृषि इनपुट की जानकारी विशेषज्ञ को दें।', 'रोकथाम और पारिस्थितिक कीट प्रबंधन को प्राथमिकता दें। केवल लक्षणों के आधार पर कीटनाशक या मात्रा न चुनें।'], 'safety': 'कीटनाशक या उर्वरक की मात्रा, उपज की भविष्यवाणी या गारंटी नहीं दी जाती। उपचार से पहले स्थानीय कृषि विशेषज्ञ से संपर्क करें।'},
 'pa': {'title': 'ਪਹਿਲਾਂ ਨਿਰੀਖਣ ਕਰੋ, ਫਿਰ ਇਲਾਜ ਚੁਣੋ', 'summary': 'ਇਹ ਆਮ ਖੇਤੀਬਾੜੀ ਮਾਰਗਦਰਸ਼ਨ ਹੈ, ਤਸ਼ਖ਼ੀਸ ਨਹੀਂ। ਉਪਲਬਧ ਜਾਣਕਾਰੀ ਨਾਲ ਬਿਮਾਰੀ, ਪੌਸ਼ਟਿਕ ਤੱਤਾਂ ਦੀ ਘਾਟ ਜਾਂ ਫ਼ਸਲ ਦੇ ਜੋਖਮ ਦੀ ਪੁਸ਼ਟੀ ਨਹੀਂ ਹੋ ਸਕਦੀ।', 'steps': ['ਪ੍ਰਭਾਵਿਤ ਅਤੇ ਸਿਹਤਮੰਦ ਪੌਦਿਆਂ ਨੂੰ ਵੇਖੋ। ਲੱਛਣ ਕਦੋਂ ਸ਼ੁਰੂ ਹੋਏ ਅਤੇ ਕੀ ਉਹ ਫੈਲ ਰਹੇ ਹਨ, ਲਿਖੋ।', 'ਕੁਦਰਤੀ ਰੌਸ਼ਨੀ ਵਿੱਚ ਪੂਰੇ ਪੌਦੇ ਅਤੇ ਪੱਤਿਆਂ ਦੇ ਦੋਵੇਂ ਪਾਸਿਆਂ ਦੀ ਫੋਟੋ ਲਓ। ਸਿੰਚਾਈ ਅਤੇ ਹਾਲੀਆ ਖੇਤੀ ਇਨਪੁਟ ਦੀ ਜਾਣਕਾਰੀ ਮਾਹਰ ਨੂੰ ਦਿਓ।', 'ਰੋਕਥਾਮ ਅਤੇ ਕੁਦਰਤੀ ਕੀਟ ਪ੍ਰਬੰਧਨ ਨੂੰ ਪਹਿਲ ਦਿਓ। ਸਿਰਫ਼ ਲੱਛਣਾਂ ਦੇ ਆਧਾਰ ਤੇ ਕੀਟਨਾਸ਼ਕ ਜਾਂ ਮਾਤਰਾ ਨਾ ਚੁਣੋ।'], 'safety': 'ਕੀਟਨਾਸ਼ਕ ਜਾਂ ਖਾਦ ਦੀ ਮਾਤਰਾ, ਝਾੜ ਦੀ ਭਵਿੱਖਬਾਣੀ ਜਾਂ ਗਾਰੰਟੀ ਨਹੀਂ ਦਿੱਤੀ ਜਾਂਦੀ। ਇਲਾਜ ਤੋਂ ਪਹਿਲਾਂ ਸਥਾਨਕ ਖੇਤੀ ਮਾਹਰ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।'},
 'or': GENERAL_ADVISORY,
}
