import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Plus, ArrowUpRight, ArrowRight, MapPin, CloudSun, Droplets, Wind, Sprout, MessagesSquare, ShieldCheck, Wheat, Lightbulb, Mic, Camera, FileText } from 'lucide-react';
import { useApp } from '../app/context';
import { useData } from '../hooks/useData';
import { useGeolocation } from '../hooks/useGeolocation';
import { useWeather } from '../hooks/useWeather';
import { Advisory, FarmField } from '../types';
import { PageHeading, SectionTitle, AdvisoryRow, ErrorNotice, Empty } from '../components/shared';
import { FieldCard } from '../components/FieldCard';
import { WeatherCard } from '../components/WeatherCard';

const DEFAULT_LOCATION_LABEL = 'Bhubaneswar, Odisha';

export default function FarmerDashboard() {
 const {user,t} = useApp(); const fields = useData<FarmField[]>('/fields', []); const cases = useData<Advisory[]>('/advisories', []);
 const geo = useGeolocation();
 useEffect(() => { geo.locate(); }, []);
 const weather = useWeather(geo.coordinates ? `latitude=${geo.coordinates[0]}&longitude=${geo.coordinates[1]}` : 'latitude=20.2961&longitude=85.8245');
 const locationLabel = weather.data?.location || user?.profile.location || geo.error || DEFAULT_LOCATION_LABEL;
 const temperatureValue = weather.data?.temperature != null ? `${Math.round(weather.data.temperature)}°C` : '—';
 const stats = [{icon:Sprout,label:t('My fields','मेरे खेत','ਮੇਰੇ ਖੇਤ'),value:fields.data.length, sub:`${fields.data.reduce((n,f)=>n+f.acreage,0)} ${t('acres under care','एकड़ देखभाल में','ਏਕੜ ਦੇਖਭਾਲ ਹੇਠ')}`,to:'/fields'}, {icon:MessagesSquare,label:t('Advisories','सलाह','ਸਲਾਹਾਂ'),value:cases.data.length,sub:t('Every question matters','हर सवाल महत्वपूर्ण है','ਹਰ ਸਵਾਲ ਮਹੱਤਵਪੂਰਨ ਹੈ'),to:'/history'}, {icon:ShieldCheck,label:t('Expert verified','विशेषज्ञ सत्यापित','ਮਾਹਰ ਤਸਦੀਕ'),value:cases.data.filter(a=>a.status==='verified').length,sub:t('A second pair of eyes','विशेषज्ञों की नज़र','ਮਾਹਰਾਂ ਦੀ ਨਜ਼ਰ'),to:'/history?status=verified'}];
 return <div className="dashboard-page"><PageHeading eyebrow={t('YOUR FARM, AT A GLANCE','आपके खेत की एक झलक','ਤੁਹਾਡੇ ਖੇਤ ਦੀ ਇੱਕ ਝਲਕ')} title={t(`Hello, ${user?.profile.name}.`,`नमस्ते, ${user?.profile.name}।`,`ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, ${user?.profile.name}।`)} description={t('A good day to grow something great.','एक अच्छी फसल की ओर एक नया दिन।','ਵਧੀਆ ਫ਼ਸਲ ਵੱਲ ਇੱਕ ਨਵਾਂ ਦਿਨ।')} action={<div className="dashboard-date"><span data-testid="dashboard-date">{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</span><span><MapPin size={13}/>{locationLabel} · {temperatureValue}</span></div>}/><ErrorNotice message={fields.error || cases.error}/>
 <div className="dashboard-hero-grid"><section className="farm-hero"><img src="/images/wheat-hero.jpg" alt="Sunlight over a lush green wheat field" fetchPriority="high"/><div className="hero-shade"/><div className="farm-hero-content"><span className="hero-eyebrow" data-testid="hero-eyebrow"><span/> {t('A COMPANION FOR EVERY SEASON','हर मौसम का साथी','ਹਰ ਮੌਸਮ ਦਾ ਸਾਥੀ')}</span><h2 data-testid="hero-heading">{t('A little care today.','आज थोड़ी देखभाल।','ਅੱਜ ਥੋੜ੍ਹੀ ਦੇਖਭਾਲ।')}<br/><em>{t('A healthier harvest tomorrow.','कल एक बेहतर फसल।','ਕੱਲ੍ਹ ਇੱਕ ਬਿਹਤਰ ਫ਼ਸਲ।')}</em></h2><p data-testid="hero-description">{t('Your field. Your questions. Guidance you can trust.','आपका खेत। आपके सवाल। भरोसेमंद मार्गदर्शन।','ਤੁਹਾਡਾ ਖੇਤ। ਤੁਹਾਡੇ ਸਵਾਲ। ਭਰੋਸੇਯੋਗ ਮਾਰਗਦਰਸ਼ਨ।')}</p><Link className="btn hero-button" to="/advisories/new" data-testid="hero-new-advisory">{t('Ask Sahaayak','सहायक से पूछें','ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ')}<ArrowUpRight size={18}/></Link></div><div className="hero-caption" data-testid="hero-caption"><Wheat size={14}/>{t('Growing together, season after season','हर मौसम, साथ बढ़ें','ਹਰ ਮੌਸਮ, ਇਕੱਠੇ ਵਧਦੇ ਹਾਂ')}</div></section>
 <WeatherCard/></div>
 <div className="stats-band">{stats.map((s,i)=><Link to={s.to} className="stat-item" key={i} data-testid={`stat-link-${i}`}><span className={`stat-icon stat-${i}`}><s.icon size={23} strokeWidth={1.5}/></span><div><p data-testid={`stat-label-${i}`}>{s.label}</p><div><strong data-testid={`stat-value-${i}`}>{s.value.toString().padStart(2,'0')}</strong><span data-testid={`stat-subtitle-${i}`}>{s.sub}</span></div></div><ArrowUpRight size={15}/></Link>)}</div>
 <div className="dashboard-lower"><section><SectionTitle title={t('Your little corner of the earth','आपकी ज़मीन का हिस्सा','ਧਰਤੀ ਦਾ ਤੁਹਾਡਾ ਹਿੱਸਾ')} to="/fields" link={t('All fields','सभी खेत','ਸਾਰੇ ਖੇਤ')}/><div className="field-cards">{fields.data.slice(0,2).map(f=><FieldCard field={f} key={f.id}/>)}</div>{!fields.data.length && <Empty title="Your next chapter starts here" description="Add your first field to get started." to="/fields" action="Add a field"/>}<Link to="/fields?add=true" data-testid="dashboard-add-field" className="add-field-inline"><Plus size={16}/>{t('Add another field','एक और खेत जोड़ें','ਇੱਕ ਹੋਰ ਖੇਤ ਜੋੜੋ')}</Link></section><section><SectionTitle title={t('Recent conversations','हाल की बातचीत','ਹਾਲੀਆ ਗੱਲਬਾਤ')} to="/history" link={t('View history','इतिहास देखें','ਇਤਿਹਾਸ ਵੇਖੋ')}/><div className="recent-advisories">{cases.data.slice(0,3).map(a=><AdvisoryRow item={a} key={a.id}/>)}</div>{!cases.data.length && <Empty title="Let’s talk about your farm" description="Your advisories will appear here." to="/advisories/new" action="Ask a question"/>}</section></div>
 <div className="daily-note"><span className="daily-note-icon"><Lightbulb size={24}/></span><div><span className="eyebrow">{t('A LITTLE WISDOM','एक छोटी सी सीख','ਥੋੜ੍ਹੀ ਸਿਆਣਪ')}</span><p data-testid="daily-tip">{t('Healthy crops begin with a closer look. Make time to walk your fields today.','स्वस्थ फसल की शुरुआत निरीक्षण से होती है। आज अपने खेत में समय बिताएँ।','ਸਿਹਤਮੰਦ ਫ਼ਸਲ ਦੀ ਸ਼ੁਰੂਆਤ ਨਿਰੀਖਣ ਨਾਲ ਹੁੰਦੀ ਹੈ। ਅੱਜ ਆਪਣੇ ਖੇਤ ਵਿੱਚ ਸਮਾਂ ਬਿਤਾਓ।')}</p></div><Link to="/knowledge" data-testid="daily-tip-source">FAO · IPM <ArrowUpRight size={15}/></Link></div>
 <div className="quick-inputs"><span>{t('However you prefer to share','अपनी पसंद से साझा करें','ਜਿਵੇਂ ਤੁਸੀਂ ਸਾਂਝਾ ਕਰਨਾ ਚਾਹੋ')}</span>{[{icon:Mic,label:t('Speak','बोलें','ਬੋਲੋ'),mode:'voice'},{icon:Camera,label:t('Take a photo','फोटो लें','ਫੋਟੋ ਲਓ'),mode:'image'},{icon:FileText,label:t('Upload a soil card','मृदा कार्ड अपलोड करें','ਮਿੱਟੀ ਕਾਰਡ ਅੱਪਲੋਡ ਕਰੋ'),mode:'soil'}].map(a=><Link key={a.mode} to={`/advisories/new?mode=${a.mode}`} data-testid={`quick-${a.mode}`}><a.icon size={17}/>{a.label}<ArrowRight size={13}/></Link>)}</div></div>;
}