import {useState} from 'react';
import {useLocation} from 'react-router-dom';
import {LocateFixed,MapPin,Loader2} from 'lucide-react';
import {useApp} from '../app/context';
import {useData} from '../hooks/useData';
import {useGeolocation} from '../hooks/useGeolocation';
import {FarmField} from '../types';
import {PageHeading,ErrorNotice} from '../components/shared';
import {FarmMap} from '../components/FarmMap';
import {WeatherCard} from '../components/WeatherCard';
export default function LocationPage(){const {t}=useApp();const {state}=useLocation();const {data:fields,error:fieldsError}=useData<FarmField[]>('/fields',[]);const geo=useGeolocation(state?.coordinates||null);const [fieldId,setFieldId]=useState('');const field=fields.find(f=>f.id===fieldId)||fields.find(f=>f.latitude!=null&&f.longitude!=null);const pin=geo.coordinates||(field?.latitude!=null&&field.longitude!=null?[field.latitude,field.longitude] as [number,number]:null);const query=geo.coordinates?`latitude=${geo.coordinates[0]}&longitude=${geo.coordinates[1]}`:field?`field_id=${field.id}`:'';return <><PageHeading eyebrow={t('YOUR PLACE, YOUR CONDITIONS','आपका स्थान, आपका मौसम','ਤੁਹਾਡੀ ਥਾਂ, ਤੁਹਾਡਾ ਮੌਸਮ')} title={t('Around your field.','आपके खेत के आसपास।','ਤੁਹਾਡੇ ਖੇਤ ਦੇ ਆਲੇ-ਦੁਆਲੇ।')} description={t('Current weather and the location you choose to share.','मौजूदा मौसम और वह स्थान जिसे आप साझा करें।','ਮੌਜੂਦਾ ਮੌਸਮ ਅਤੇ ਉਹ ਥਾਂ ਜੋ ਤੁਸੀਂ ਸਾਂਝੀ ਕਰੋ।')} action={<button className="btn primary" data-testid="location-use-gps" disabled={geo.locating} onClick={geo.locate}>{geo.locating?<Loader2 className="spin" size={17}/>:<LocateFixed size={17}/>} {t('Use my location','मेरा स्थान उपयोग करें','ਮੇਰੀ ਥਾਂ ਵਰਤੋ')}</button>}/><ErrorNotice message={geo.error||fieldsError}/><div className="location-layout"><section><div className="location-picker"><label htmlFor="location-field">{t('Saved field','सहेजा गया खेत','ਸੰਭਾਲਿਆ ਖੇਤ')}</label><select id="location-field" data-testid="location-field-select" value={geo.coordinates?'':field?.id||''} onChange={e=>{setFieldId(e.target.value);geo.setCoordinates(null);}}><option value="" label={geo.coordinates?'Your shared location':'Select a mapped field'}/>{fields.map(f=><option key={f.id} value={f.id} label={`${f.name} · ${f.location}`}/>)}</select></div><FarmMap fields={geo.coordinates?[]:field?[field]:[]} selected={geo.coordinates} onSelect={(lat,lon)=>geo.setCoordinates([lat,lon])}/><p className="location-coordinates" data-testid="location-coordinates"><MapPin size={14}/>{pin?`${pin[0].toFixed(5)}, ${pin[1].toFixed(5)}`:t('No location shared','कोई स्थान साझा नहीं किया गया','ਕੋਈ ਥਾਂ ਸਾਂਝੀ ਨਹੀਂ ਕੀਤੀ ਗਈ')}</p><p className="location-privacy" data-testid="location-privacy">{t('Location is requested only when you choose it. No background tracking. Coordinates are sent to the map/weather provider to display local conditions.','स्थान केवल आपकी अनुमति पर लिया जाता है। पृष्ठभूमि में ट्रैकिंग नहीं होती। मौसम और नक्शे के लिए निर्देशांक सेवा प्रदाता को भेजे जाते हैं।','ਥਾਂ ਸਿਰਫ਼ ਤੁਹਾਡੀ ਇਜਾਜ਼ਤ ਨਾਲ ਲਈ ਜਾਂਦੀ ਹੈ। ਪਿਛੋਕੜ ਵਿੱਚ ਟਰੈਕਿੰਗ ਨਹੀਂ ਹੁੰਦੀ। ਮੌਸਮ ਅਤੇ ਨਕਸ਼ੇ ਲਈ ਕੋਆਰਡੀਨੇਟ ਸੇਵਾ ਪ੍ਰਦਾਤਾ ਨੂੰ ਭੇਜੇ ਜਾਂਦੇ ਹਨ।')}</p></section><WeatherCard query={query} locationControls={false}/></div></>;}